name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Test
        run: npx jest --reporters=default jest-html-reporters
      - name: Upload artifact and Generate Report
        uses: actions/upload-artifact@v2
        with:
          name: Jest Report
          path: reports/html-report/report.html
      - name: Copy Jest HTML Reporter files
        run: |
          mkdir -p jest-html-reporters-attach/report
          cp $GITHUB_WORKSPACE/node_modules/jest-html-reporter/lib/index.js jest-html-reporters-attach/report/
          cp $GITHUB_WORKSPACE/node_modules/jest-html-reporter/lib/result.js jest-html-reporters-attach/report/

          
      



