name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Test and Generate Report
        run: |
          npx jest
          mv ./reports/html-report/report.html ./report.html
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Jest Report
          path: reports/html-report/report.html


